//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Scripts/PlayerСontrol.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerСontrol : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerСontrol()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerСontrol"",
    ""maps"": [
        {
            ""name"": ""ProMotion"",
            ""id"": ""b75ca10f-f55a-45c6-8e12-36efe3b7ea54"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""2dd4d46e-df57-43e6-bdda-baa70cc557c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""f16ff4e7-1c86-4017-8027-1755c5cb7fd2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""Value"",
                    ""id"": ""3cb928e0-4974-4a78-8270-8bce6b4e182c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ZRotation"",
                    ""type"": ""Value"",
                    ""id"": ""5f6f093d-0d94-4d21-9c36-d2658e54a6d2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchGravity"",
                    ""type"": ""Button"",
                    ""id"": ""2db0f618-dd73-4673-ac4b-5f19b56aff7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartBoost"",
                    ""type"": ""Button"",
                    ""id"": ""1f9acff4-6e70-47b4-984b-b8acae0b94c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a9627e01-ec16-4798-8f12-1b19515c9a6c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3c31882-44a7-4bf3-89dc-64100fef7034"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""6ce9016f-26b7-4e50-b575-3096014c8bb6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""54cb831c-c232-403f-8ae4-3f2d50bd6fa6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a2b31650-3f52-4a63-a757-7971b99a1f15"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ed4ae129-50fb-418a-889f-7ce03d8ec51a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3a11a89b-c5e6-4bff-8dbb-f756e97865a8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keys"",
                    ""id"": ""9a8e6ab7-b22c-4d20-8e9c-fd9390f72928"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ce45feb8-e1ba-470c-b9fd-5b47a8921428"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""93cf3907-3347-485f-8052-9696fcf86242"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2af7a1b1-cca2-4885-ba45-a5c2dbfe1ee5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1b6d0e24-0e78-470f-8119-eb7b1f0d2eed"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8429e39f-88af-4fce-b992-2ac3adc598d5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eba2fafc-02f3-47e0-a9c1-b40da81a4b3f"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24945c0f-e30b-4c3e-a845-3b38623f71da"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""0585c720-28cf-4407-b5f7-0b16e27ade65"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZRotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2a906e20-a42c-4d79-b647-31641a588661"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ZRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""953c074c-7767-4d41-8f43-9cc4e7846971"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ZRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""242887d3-135f-4b95-9c85-770b9ab26922"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZRotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9bb28e8d-33c9-496c-98fb-2f03c3a599bb"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""ZRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9c77dbe8-3a30-476b-b58e-671df24e850f"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""ZRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cf708d1c-25a0-4907-80f2-c176876d1c06"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SwitchGravity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f3ac378-997d-4937-a1d3-006b6099d273"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""SwitchGravity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d164fa10-21ed-4660-b16f-1312cd13ed0d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""StartBoost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""405fb688-415c-4b1a-aefa-ecee3b5d88b9"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""StartBoost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Xbox"",
            ""bindingGroup"": ""Xbox"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // ProMotion
        m_ProMotion = asset.FindActionMap("ProMotion", throwIfNotFound: true);
        m_ProMotion_Jump = m_ProMotion.FindAction("Jump", throwIfNotFound: true);
        m_ProMotion_Movement = m_ProMotion.FindAction("Movement", throwIfNotFound: true);
        m_ProMotion_Camera = m_ProMotion.FindAction("Camera", throwIfNotFound: true);
        m_ProMotion_ZRotation = m_ProMotion.FindAction("ZRotation", throwIfNotFound: true);
        m_ProMotion_SwitchGravity = m_ProMotion.FindAction("SwitchGravity", throwIfNotFound: true);
        m_ProMotion_StartBoost = m_ProMotion.FindAction("StartBoost", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ProMotion
    private readonly InputActionMap m_ProMotion;
    private IProMotionActions m_ProMotionActionsCallbackInterface;
    private readonly InputAction m_ProMotion_Jump;
    private readonly InputAction m_ProMotion_Movement;
    private readonly InputAction m_ProMotion_Camera;
    private readonly InputAction m_ProMotion_ZRotation;
    private readonly InputAction m_ProMotion_SwitchGravity;
    private readonly InputAction m_ProMotion_StartBoost;
    public struct ProMotionActions
    {
        private @PlayerСontrol m_Wrapper;
        public ProMotionActions(@PlayerСontrol wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_ProMotion_Jump;
        public InputAction @Movement => m_Wrapper.m_ProMotion_Movement;
        public InputAction @Camera => m_Wrapper.m_ProMotion_Camera;
        public InputAction @ZRotation => m_Wrapper.m_ProMotion_ZRotation;
        public InputAction @SwitchGravity => m_Wrapper.m_ProMotion_SwitchGravity;
        public InputAction @StartBoost => m_Wrapper.m_ProMotion_StartBoost;
        public InputActionMap Get() { return m_Wrapper.m_ProMotion; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ProMotionActions set) { return set.Get(); }
        public void SetCallbacks(IProMotionActions instance)
        {
            if (m_Wrapper.m_ProMotionActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnJump;
                @Movement.started -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnMovement;
                @Camera.started -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnCamera;
                @Camera.performed -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnCamera;
                @Camera.canceled -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnCamera;
                @ZRotation.started -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnZRotation;
                @ZRotation.performed -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnZRotation;
                @ZRotation.canceled -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnZRotation;
                @SwitchGravity.started -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnSwitchGravity;
                @SwitchGravity.performed -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnSwitchGravity;
                @SwitchGravity.canceled -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnSwitchGravity;
                @StartBoost.started -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnStartBoost;
                @StartBoost.performed -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnStartBoost;
                @StartBoost.canceled -= m_Wrapper.m_ProMotionActionsCallbackInterface.OnStartBoost;
            }
            m_Wrapper.m_ProMotionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Camera.started += instance.OnCamera;
                @Camera.performed += instance.OnCamera;
                @Camera.canceled += instance.OnCamera;
                @ZRotation.started += instance.OnZRotation;
                @ZRotation.performed += instance.OnZRotation;
                @ZRotation.canceled += instance.OnZRotation;
                @SwitchGravity.started += instance.OnSwitchGravity;
                @SwitchGravity.performed += instance.OnSwitchGravity;
                @SwitchGravity.canceled += instance.OnSwitchGravity;
                @StartBoost.started += instance.OnStartBoost;
                @StartBoost.performed += instance.OnStartBoost;
                @StartBoost.canceled += instance.OnStartBoost;
            }
        }
    }
    public ProMotionActions @ProMotion => new ProMotionActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_XboxSchemeIndex = -1;
    public InputControlScheme XboxScheme
    {
        get
        {
            if (m_XboxSchemeIndex == -1) m_XboxSchemeIndex = asset.FindControlSchemeIndex("Xbox");
            return asset.controlSchemes[m_XboxSchemeIndex];
        }
    }
    public interface IProMotionActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnZRotation(InputAction.CallbackContext context);
        void OnSwitchGravity(InputAction.CallbackContext context);
        void OnStartBoost(InputAction.CallbackContext context);
    }
}
